apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tutorial-pipeline
spec:
  workspaces:
    - name: myworkspace
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: myworkspace
      params:
        - name: url
<<<<<<< HEAD
          value: https://github.com/prane12/budget-app-new.git 
=======
          value: https://github.com/prane12/Budget-App.git
>>>>>>> e98b0c87f65beb818d2a71c6ea69c4b45aed3c14
        - name: deleteExisting
          value: "true"
    - name: build
      taskRef:
        name: buildah
      runAfter:
        - git-clone
      params:
        - name: IMAGE
          value: docker.io/prane12/budget-app
        - name: IMAGE_PUSH_SECRET_NAME
          value: image-push-secrets
      workspaces:
        - name: source
          workspace: myworkspace
