# docker-compose.yml

version: '3.9'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env  # Specify the path to your .env file
    environment: 
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
<<<<<<< HEAD
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rake db:migrate && bundle exec rails server -b 0.0.0.0"

=======
>>>>>>> e98b0c87f65beb818d2a71c6ea69c4b45aed3c14
  db:
    image: postgres:14.1
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"

