apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budget-app
  template:
    metadata:
      labels:
        app: budget-app
    spec:
      initContainers:
      - name: migrate
        image: prane12/budget-app-repo:latest
        command: ["bin/rails", "db:migrate", "RAILS_ENV=development"]
        env:
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_USER
          value: "Budgy"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_PASSWORD
        - name: DB_NAME
          value: "budgy_development"
        - name: DB_PORT
          value: "5432"
      containers:
      - name: budget-app
        image: prane12/budget-app-repo:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_USER
          value: "Budgy"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_PASSWORD
        - name: DB_NAME
          value: "budgy_development"
        - name: DB_PORT
          value: "5432"

