apiVersion: v1
kind: Service
metadata:
  name: budget-app-service
  labels:
    app: budget-app
spec:
  selector:
    app: budget-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 31000
  type: NodePort

