apiVersion: v1
kind: Service
metadata:
  name: postgres-service 
  labels:
    app: database
spec:
  clusterIP: None
  selector:
    app: database
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
