default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") %>
  port: <%= ENV.fetch("DB_PORT") %>
  database: <%= ENV.fetch("DB_NAME") %>
  host: <%= ENV.fetch("DB_HOST") %>
  username: <%= ENV.fetch("DB_USER") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST") %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_PRODUCTION") %>

