apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  # example of adding additional configuration
  repositories: |
    - url: https://github.com/prane12/budget-app-new.git
      type: git
      passwordSecret:
        name: github-cred
        key: password
      usernameSecret:
        name: github-cred
        key: username

